### ISSUE TITLE
When speed slider moved to zero and back up the animation stops

### ISSUE THREAD

**Issue by countgizmo** [dimovich/art#1]
It happens every time you move speed slider to zero.
It seems that the only way to restart the animation is to fiddle with other sliders or refresh.

**Comment by dimovich** [comment]
The speed slider acts as a speed limit. I think it should be renamed to "max speed".

The agents don't generate their own speed. They simply react to the movement of neighboring agents. So when you set the speed to 0 and stop all of them, there is no acting forces that will make them move again when you set the speed to 1. You have to increase at least one of the forces (cohesion, separation or alignment) to make them move.

Initially when you create them, they all have random starting speed, but after that - it's all about the motion of the neighbors.

(I will try giving them a constant intrinsic speed, see what happens).

A nice experiment is setting all sliders to 0 (except radius and separation), and then slowly increase the speed. You will notice that initially the agents are in a state of equilibrium, but slowly they start affecting each other and makes the system alive again.

![agents-speed](https://user-images.githubusercontent.com/41097/35154991-ed1bcdc2-fd34-11e7-8e3d-90180f1d4f91.gif)

**Comment by countgizmo** [comment]
Thanks for the explanation, sir! Good work.
